# Generated by Django 4.2.4 on 2023-08-31 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("recognition", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="licenseplateinfo", name="owner",),
        migrations.AddField(
            model_name="licenseplateinfo",
            name="user",
            field=models.ForeignKey(
                default="用户已注销",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="accounts.userinfo",
                to_field="username",
                verbose_name="用户",
            ),
        ),
    ]
