# Generated by Django 4.2.4 on 2023-08-31 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0002_remove_licenseplateinfo_owner_licenseplateinfo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplateinfo",
            name="recognition_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 31, 17, 38, 38, 910122),
                verbose_name="识别时间",
            ),
        ),
    ]
