# Generated by Django 4.2.4 on 2023-08-31 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0003_alter_licenseplateinfo_recognition_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenseplateinfo",
            name="file",
            field=models.FileField(default="", upload_to="images/", verbose_name="文件"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="licenseplateinfo",
            name="recognition_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 31, 20, 44, 52, 19672),
                verbose_name="识别时间",
            ),
        ),
    ]
