# Generated by Django 4.2.4 on 2023-09-02 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0004_licenseplateinfo_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplateinfo",
            name="recognition_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 2, 15, 17, 6, 344241),
                verbose_name="识别时间",
            ),
        ),
        migrations.AlterField(
            model_name="licenseplateinfo",
            name="user",
            field=models.CharField(default="用户已注销", max_length=32, verbose_name="用户"),
        ),
    ]
