# Generated by Django 4.2.11 on 2024-05-29 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0007_alter_licenseplateinfo_recognition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplateinfo',
            name='recognition_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 3, 33, 43, 937051), verbose_name='识别时间'),
        ),
    ]
